# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View Created Accounts - Table.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(601, 683)
        MainWindow.setMinimumSize(QtCore.QSize(601, 683))
        MainWindow.setMaximumSize(QtCore.QSize(601, 683))
        MainWindow.setStyleSheet("#title{\n"
"    background-color: #860f0f;\n"
"    color: white;\n"
"}\n"
"\n"
"\n"
"QTableWidget{\n"
"    border: 1px solid black;\n"
"}")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 0, 601, 91))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(28)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.createdAccountsTable = QtWidgets.QTableWidget(self.centralwidget)
        self.createdAccountsTable.setGeometry(QtCore.QRect(20, 110, 561, 561))
        self.createdAccountsTable.setAutoFillBackground(False)
        self.createdAccountsTable.setStyleSheet("QHeaderView::section{\n"
"    border: none;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.createdAccountsTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.createdAccountsTable.setFrameShadow(QtWidgets.QFrame.Plain)
        self.createdAccountsTable.setLineWidth(2)
        self.createdAccountsTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.createdAccountsTable.setDragDropOverwriteMode(False)
        self.createdAccountsTable.setAlternatingRowColors(True)
        self.createdAccountsTable.setTextElideMode(QtCore.Qt.ElideRight)
        self.createdAccountsTable.setGridStyle(QtCore.Qt.SolidLine)
        self.createdAccountsTable.setWordWrap(True)
        self.createdAccountsTable.setCornerButtonEnabled(True)
        self.createdAccountsTable.setObjectName("createdAccountsTable")
        self.createdAccountsTable.setColumnCount(7)
        self.createdAccountsTable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.createdAccountsTable.setItem(1, 6, item)
        self.createdAccountsTable.horizontalHeader().setCascadingSectionResizes(False)
        self.createdAccountsTable.horizontalHeader().setDefaultSectionSize(150)
        self.createdAccountsTable.horizontalHeader().setSortIndicatorShown(True)
        self.createdAccountsTable.horizontalHeader().setStretchLastSection(False)
        self.createdAccountsTable.verticalHeader().setVisible(False)
        self.createdAccountsTable.verticalHeader().setCascadingSectionResizes(False)
        self.createdAccountsTable.verticalHeader().setDefaultSectionSize(30)
        self.createdAccountsTable.verticalHeader().setStretchLastSection(False)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "View Created Accounts"))
        self.title.setText(_translate("MainWindow", "View Created Accounts"))
        self.createdAccountsTable.setSortingEnabled(False)
        item = self.createdAccountsTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.createdAccountsTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.createdAccountsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No."))
        item = self.createdAccountsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Email Address"))
        item = self.createdAccountsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.createdAccountsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.createdAccountsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Org Unit Path"))
        item = self.createdAccountsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Recovery Email"))
        item = self.createdAccountsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Password"))
        __sortingEnabled = self.createdAccountsTable.isSortingEnabled()
        self.createdAccountsTable.setSortingEnabled(False)
        item = self.createdAccountsTable.item(0, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.createdAccountsTable.item(0, 1)
        item.setText(_translate("MainWindow", "rdpugoy@up.edu.ph"))
        item = self.createdAccountsTable.item(0, 2)
        item.setText(_translate("MainWindow", "Reinald"))
        item = self.createdAccountsTable.item(0, 3)
        item.setText(_translate("MainWindow", "Pugoy"))
        item = self.createdAccountsTable.item(0, 4)
        item.setText(_translate("MainWindow", "/Students/UP Open University Students/Active UPOU Students"))
        item = self.createdAccountsTable.item(0, 5)
        item.setText(_translate("MainWindow", "radlp.kr@gmail.com"))
        item = self.createdAccountsTable.item(0, 6)
        item.setText(_translate("MainWindow", "D2ge14ouM!"))
        item = self.createdAccountsTable.item(1, 0)
        item.setText(_translate("MainWindow", "2"))
        item = self.createdAccountsTable.item(1, 1)
        item.setText(_translate("MainWindow", "rdpugoy@up.edu.ph"))
        item = self.createdAccountsTable.item(1, 2)
        item.setText(_translate("MainWindow", "Reinald"))
        item = self.createdAccountsTable.item(1, 3)
        item.setText(_translate("MainWindow", "Pugoy"))
        item = self.createdAccountsTable.item(1, 4)
        item.setText(_translate("MainWindow", "/Students/UP Open University Students/Active UPOU Students"))
        item = self.createdAccountsTable.item(1, 5)
        item.setText(_translate("MainWindow", "radlp.kr@gmail.com"))
        item = self.createdAccountsTable.item(1, 6)
        item.setText(_translate("MainWindow", "D2ge14ouM!"))
        self.createdAccountsTable.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
